include:
  - "/ci-scripts/release/release.yml"
  - "/ci-scripts/test/aval-tests.yml"
  - "/ci-scripts/test/dotnet-tests.yml"
  - "/ci-scripts/test/support-files-tests.yml"
  - "/ci-scripts/build/upstream.yml"
  - "/ci-scripts/build/imx8.yml"
  - "/ci-scripts/build/am62.yml"
  - "/ci-scripts/lint/lint.yml"

image: docker:latest

variables:
  DEBIAN_POINT_RELEASE: "12.8-slim"
  TORADEX_INTERNAL_DOCKERHUB_CACHE: "artifactory-horw.int.toradex.com/dockerhub-proxy-no-cache-horw"
  # This should be set by docker image already, just to be sure...
  DOCKER_HOST: tcp://docker:2375
  # Use overlayfs driver for better performance
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

  PLATFORM_SPECIFIC_FOLDER: "platform-specific"
  SUPPORT_FILES_FOLDER: "support-files"
  IMX8_FOLDER: "imx8"
  AM62_FOLDER: "am62"
  UPSTREAM_FOLDER: "upstream"
  TESTS_FOLDER: "tests"
  TESTS_CONTAINERS_FOLDER: "containers"
  CHROMIUM_TESTS_FOLDER: "chromium-tests"
  CROSS_TOOLCHAIN_FOLDER: "cross-toolchain"
  DOTNET_FOLDER: "dotnet"
  SSH_FOLDER: "ssh"
  BASE_FOLDER: "base"
  WAYLAND_BASE_FOLDER: "wayland-base"
  GTK_3_FOLDER: "gtk3"
  GTK_3_TESTS_FOLDER: "gtk3-tests"
  WESTON_FOLDER: "weston"
  GRAPHICS_TESTS_FOLDER: "graphics-tests"
  WESTON_TOUCH_CALIBRATOR_FOLDER: "weston-touch-calibrator"
  QT_TESTS_FOLDER: "qt-tests"
  QT5_WAYLAND_FOLDER: "qt5-wayland"
  QT6_WAYLAND_FOLDER: "qt6-wayland"
  QT5_WAYLAND_EXAMPLES_FOLDER: "qt5-wayland-examples"
  QT6_WAYLAND_EXAMPLES_FOLDER: "qt6-wayland-examples"
  QT6_TESTS_FOLDER: "qt6-wayland-tests"
  DOTNET_BASE_FOLDER: "base"
  DOTNET_DEBUG_FOLDER: "debug"
  DOTNET_WAYLAND_BASE_FOLDER: "wayland-base"
  DOTNET_WAYLAND_DEBUG_FOLDER: "wayland-debug"
  RT_VALIDATION_FOLDER: "rt-validation"
  RT_TESTS_FOLDER: "rt-tests"
  STRESS_TESTS_FOLDER: "stress-tests"
  CHROMIUM_FOLDER: "chromium"
  COG_FOLDER: "cog"

services:
  - name: docker:dind

.include-regctl:
  before_script:
    - apk update && apk add curl
    - curl -L https://github.com/regclient/regclient/releases/download/v0.6.0/regctl-linux-amd64 > /usr/bin/regctl
    # to update the hash: download the metadata the regctl repo, verify the signatures, generate the SHA256SUMS file
    # with `sha256sum -b regctl > SHA256SUMS` and update it here.
    - echo "44216c0ab3bd41ae30b07392d6cdab6971f48ab3f72400e617f5f0ded4d70742 /usr/bin/regctl" > SHA256SUMS
    - if ! sha256sum -c SHA256SUMS; then echo "Checksum for regctl has failed"; fi
    - chmod 755 /usr/bin/regctl
    - regctl registry login docker.io -u $DOCKERHUB_USER -p $DOCKERHUB_TOKEN

.do_print_environment_variables: &do_print_environment_variables
  - echo "GitLab CI/CD environment variables:"
  - env

.docker-configure:
  script:
    - apk add bash
    - ./ci-scripts/configure/docker-buildx-configure.sh

.docker-build:
  extends: .docker-configure
  variables:
    ADD_TORADEX_REPOSITORY: 1
  script:
    - !reference [.docker-configure, script]
    - *do_print_environment_variables
    - apk add curl bash
    - ./ci-scripts/build/docker-build.sh
